//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Aplikacija.Jezici {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Moji_Resursi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Moji_Resursi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_Aplikacija.Jezici.Moji_Resursi", typeof(Moji_Resursi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalje.
        /// </summary>
        internal static string Dalje {
            get {
                return ResourceManager.GetString("Dalje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        internal static string Detalji {
            get {
                return ResourceManager.GetString("Detalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan:.
        /// </summary>
        internal static string lbCaptain {
            get {
                return ResourceManager.GetString("lbCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji O Reprezentaciji.
        /// </summary>
        internal static string lbDetaljiORepki {
            get {
                return ResourceManager.GetString("lbDetaljiORepki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOMAĆI TIM.
        /// </summary>
        internal static string lbDomaciTim {
            get {
                return ResourceManager.GetString("lbDomaciTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi:.
        /// </summary>
        internal static string lbGoals {
            get {
                return ResourceManager.GetString("lbGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOSTUJUĆI TIM.
        /// </summary>
        internal static string lbGostujuciTim {
            get {
                return ResourceManager.GetString("lbGostujuciTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gubici:.
        /// </summary>
        internal static string lbGubici {
            get {
                return ResourceManager.GetString("lbGubici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        internal static string lbIme {
            get {
                return ResourceManager.GetString("lbIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa Kod:.
        /// </summary>
        internal static string lbKod {
            get {
                return ResourceManager.GetString("lbKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv:.
        /// </summary>
        internal static string lbName {
            get {
                return ResourceManager.GetString("lbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodlucene:.
        /// </summary>
        internal static string lbNeodluceni {
            get {
                return ResourceManager.GetString("lbNeodluceni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj:.
        /// </summary>
        internal static string lbNumber {
            get {
                return ResourceManager.GetString("lbNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite Prvenstvo.
        /// </summary>
        internal static string lbOdabirPrvenstva {
            get {
                return ResourceManager.GetString("lbOdabirPrvenstva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrane:.
        /// </summary>
        internal static string lbOdigrani {
            get {
                return ResourceManager.GetString("lbOdigrani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobijede:.
        /// </summary>
        internal static string lbPobijede {
            get {
                return ResourceManager.GetString("lbPobijede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        internal static string lbPosition {
            get {
                return ResourceManager.GetString("lbPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljeni:.
        /// </summary>
        internal static string lbPrimljeni {
            get {
                return ResourceManager.GetString("lbPrimljeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika:.
        /// </summary>
        internal static string lbRazlika {
            get {
                return ResourceManager.GetString("lbRazlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuti Kart:.
        /// </summary>
        internal static string lbYellows {
            get {
                return ResourceManager.GetString("lbYellows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijeni:.
        /// </summary>
        internal static string lbZabijeni {
            get {
                return ResourceManager.GetString("lbZabijeni", resourceCulture);
            }
        }
    }
}
