//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Forms_Aplikacija.Jezici {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Moji_Resursi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Moji_Resursi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows_Forms_Aplikacija.Jezici.Moji_Resursi", typeof(Moji_Resursi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natrag.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalje.
        /// </summary>
        internal static string btnDalje {
            get {
                return ResourceManager.GetString("btnDalje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        internal static string btnPrijevodOpcije {
            get {
                return ResourceManager.GetString("btnPrijevodOpcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        internal static string btnSpremi {
            get {
                return ResourceManager.GetString("btnSpremi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ucitaj Sliku:.
        /// </summary>
        internal static string btnUcitajSliku {
            get {
                return ResourceManager.GetString("btnUcitajSliku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natrag.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gosti.
        /// </summary>
        internal static string lbAwayTeam {
            get {
                return ResourceManager.GetString("lbAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaci.
        /// </summary>
        internal static string lbHomeTeam {
            get {
                return ResourceManager.GetString("lbHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        internal static string lbIme {
            get {
                return ResourceManager.GetString("lbIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime Igraca.
        /// </summary>
        internal static string lbImeKartoni {
            get {
                return ResourceManager.GetString("lbImeKartoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik Aplikacije.
        /// </summary>
        internal static string lbJezikOpcije {
            get {
                return ResourceManager.GetString("lbJezikOpcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        internal static string lbLokacija {
            get {
                return ResourceManager.GetString("lbLokacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najvise Golova.
        /// </summary>
        internal static string lbNaslovGolovi {
            get {
                return ResourceManager.GetString("lbNaslovGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najvise Zutih Kartona.
        /// </summary>
        internal static string lbNaslovKartoni {
            get {
                return ResourceManager.GetString("lbNaslovKartoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posjecenost Po Utakmicama.
        /// </summary>
        internal static string lbNaslovPosjecenost {
            get {
                return ResourceManager.GetString("lbNaslovPosjecenost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir Prvenstva.
        /// </summary>
        internal static string lbOdabir {
            get {
                return ResourceManager.GetString("lbOdabir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite Omiljenu Reprezentaciju.
        /// </summary>
        internal static string lbOmiljenaRepka {
            get {
                return ResourceManager.GetString("lbOmiljenaRepka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljeni Igraci.
        /// </summary>
        internal static string lbOmiljeni {
            get {
                return ResourceManager.GetString("lbOmiljeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        internal static string lbPrezime {
            get {
                return ResourceManager.GetString("lbPrezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime Igraca.
        /// </summary>
        internal static string lbPrezimeKartoni {
            get {
                return ResourceManager.GetString("lbPrezimeKartoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljena Reprezentacija.
        /// </summary>
        internal static string lbRepkaOpcije {
            get {
                return ResourceManager.GetString("lbRepkaOpcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis Igraca.
        /// </summary>
        internal static string lbSviIgraci {
            get {
                return ResourceManager.GetString("lbSviIgraci", resourceCulture);
            }
        }
    }
}
